### ISSUE TITLE
Countdown Cog 

### ISSUE THREAD

**Issue by Alfred-PictoCube** [KrazySoft/Krazy-Cogs#1]
When issuing **[p]** countdown seconds title : 

"Error in command 'countdown'. Check your console or logs for details"

Log details : 
```
ERROR red on_command_error 369: Exception in command 'countdown'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/****/Red-DiscordBot/cogs/countdown.py", line 23, in countdown
    channelID = ctx.channel.id
AttributeError: 'Context' object has no attribute 'channel'
```

**Comment by KrazySoft** [comment]
Issue Resolved thank you for bringing it to my attention.
